Refactor builtins
LucasKuhn/minishell pull request #33
Opened 2022-06-05 22:29 UTC by LucasKuhn

- Fixes all TODOs from builtins 
- Norminette check OK 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/26127185/172073206-77529b63-b2d6-402f-b812-08b0d426dda2.png">

2022-06-05 23:11 UTC, LucasKuhn commented on .github/workflows/tester.yml
> +    branches: [ "**" ]
Pra rodar o teste em todos os branches, mesmo se não tem um pull request

2022-06-05 23:23 UTC, LucasKuhn commented on builtins/exit.c
> +	exit_status = ft_atoll(args[1]);
Adicionei a nossa própria `ft_atoll` nas utils

2022-06-05 23:31 UTC, LucasKuhn commented on builtins/export.c
> +		}
Adicionei esse teste nos pipes, que é tipo o `env` que precisa de um `sort` pra dar certo
Ali eu vi que além de escrever `declare -x` o export sem nada coloca o valor da variável entre aspas, ex: 
```sh
declare -x HELLO="world"
```

2022-06-06 00:01 UTC, sgkhusal commented on builtins/exit.c
>  	close_all_fds();
Colocar para fechar os fds antes do check_args_error para evitar fds abertos no caso de erro.

2022-06-06 00:05 UTC, sgkhusal commented on builtins/export.c
> +		}
Que bom que a gente já tinha a name_only e a value_only =)
Nem tinha percebido a parte das aspas

2022-06-06 00:10 UTC, sgkhusal commented on builtins/export.c
> +		print_error_msg(varname, "not a valid identifier");
Fica faltando o export na mensagem de erro (meu toc não gosta disso rsrs)

2022-06-06 00:13 UTC, sgkhusal commented on minienv/minienv.c
> +		list_append("OLDPWD", &list);
Achei muito boa a sacada de colocar a OLDPWD logo que cria a minienv, se ela não existir

2022-06-06 00:33 UTC, sgkhusal requested changes
Muito bom, tenho dois pontos para modificar:
- Em builtins/exit.c, na função builtin_exit, colocar para fechar os fds antes da função check_args_error para evitar fds abertos no caso de erro (inverter linhas 71 e 72);
- Em builtins/export.c, creio que usar a função print_error_msg vai tirar o 'export' da mensagem de erro (não sei se é preciosismo da minha parte, mas o meu toc não gosta rsrs). Por exemplo, ao invés de termos uma mensagem do tipo "minishell: export: varname: ..." ficaria "minishell: varname: ...". Acaba destoando do padrão que estamos seguindo para as mensagens de erro... Penso que uma solução para poder utilizar a print_error_msg seria mandar uma str que junta "export: varname", mas não sei se é a melhor solução, porque teríamos que dar free depois nela também...

2022-06-06 00:42 UTC, LucasKuhn commented on minienv/minienv.c
> +		list_append("OLDPWD", &list);
Esse eu descobri por causa do `export` sem argumentos que faz o esquema de listar as coisas com `declare -x` 
No teste deu diferença que vi que o próprio bash cria um `OLDPWD` quando não tem hehe

2022-06-06 00:45 UTC, LucasKuhn commented on builtins/export.c
> +		print_error_msg(varname, "not a valid identifier");
Nem me liguei que ficava sem o `export: `, coloquei de volta (;

2022-06-06 01:01 UTC, sgkhusal approved these changes
Muito bom!

2022-06-06 01:01 UTC, merged